<html>
<body>
<?php 

?>
<p><br>Want to add or remove some items? Go back to main menu.</br></p>
<form action="/index.html">
	<input type="submit" value="Back to main menu">
</form>

<h><br>Please provide your card details</br></h>
<form action="">
	User:<br>
	<input type="text" name="user"> <br>
	Password:<br>
	<input type="text" name="pass"> <br>
	<input type="submit" value="submit">
</form>

<p><br>View items added to cart?</br></p>
<form action="/view.phtml" target="_blank">
	<input type="submit" value="View cart">
</form>

</body>
</html>
